-- V2__create_postmortems.sql
-- Creates the 'postmortems' table with a FK to incidents and indexed incident_id.
-- Optional sections (contributing_factors, action_items, lessons_learned,
-- exported_markdown) are nullable — the export layer omits them when NULL,
-- per ADR-005 (JSON Schema with mandatory and optional sections).

CREATE TABLE postmortems (
    id                    UUID  NOT NULL,
    incident_id           UUID  NOT NULL,

    -- Mandatory sections (always generated by the LLM pipeline)
    title                 VARCHAR(512) NOT NULL,
    summary               TEXT         NOT NULL,
    timeline              TEXT         NOT NULL,
    root_cause            TEXT         NOT NULL,
    impact                TEXT         NOT NULL,
    detection             TEXT         NOT NULL,

    -- Optional sections (null when insufficient data — ADR-005)
    contributing_factors  TEXT,
    action_items          TEXT,
    lessons_learned       TEXT,
    exported_markdown     TEXT,

    created_at            TIMESTAMP    NOT NULL,

    CONSTRAINT pk_postmortems    PRIMARY KEY (id),
    CONSTRAINT fk_postmortems_incident
        FOREIGN KEY (incident_id) REFERENCES incidents (id)
        ON DELETE CASCADE
);

-- Index on incident_id to support FK lookups and join queries
CREATE INDEX idx_postmortems_incident_id ON postmortems (incident_id);
